### ISSUE TITLE
Rain Probability 

### ISSUE THREAD

**Issue by eracknaphobia** [kalkih/simple-weather-card#13]
It would be awesome if we could display the precipitation probability instead of amount.

**Comment by kalkih** [comment]
I could see that being useful!

I've not yet seen any weather component with support for rain probability though (haven't tried all).
Does the one you use expose it?

**Comment by eracknaphobia** [comment]
Thanks for the quick response!. Yes, I use [dark sky](https://www.home-assistant.io/components/darksky/) for weather:

 ```
 - platform: darksky
    api_key: !secret darksky_api_key
    scan_interval: '00:05:00'
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - temperature
      - apparent_temperature
      - temperature_high
      - temperature_low
      - humidity
      - precip_probability
      - precip_intensity
      - precip_type
      - wind_speed
      - wind_bearing
      - pressure
      - icon
      - hourly_summary
      - daily_summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - apparent_temperature_high
      - apparent_temperature_low
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
```
