### ISSUE TITLE
When data source is missing, entire page doesn't show up

### ISSUE THREAD

**Issue by j0dan** [kalkih/simple-weather-card#15]
If my dark sky sensors are broken, the entire lovelace page is blank when using this custom card.

```
      - custom:
          - temp: sensor.netatmo_outdoor_temperature
          - high: sensor.dark_sky_daytime_high_temperature_0d
          - low: sensor.dark_sky_overnight_low_temperature_0d
        entity: weather.dark_sky
        type: 'custom:simple-weather-card'
```
