### ISSUE TITLE
Wind speed

### ISSUE THREAD

**Issue by alexpod93** [kalkih/simple-weather-card#21]
Hello! Is it possible to change wind speed from "km/h" to "m/s"?

**Comment by kalkih** [comment]
Hello,
km/h and mph seems to be the standard measurement of wind speed in HA.
You can however override the wind_speed information of this card with your own sensor, so you could provide it with a sensor where you got the unit of measurement and speed in m/s.
```yaml
- type: custom:simple-weather-card
  entity: weather.smhi_home
  custom:
    - wind_speed: sensor.wind_in_ms
```

Thanks!
