### ISSUE TITLE
TypeError: E[A] is undefined

### ISSUE THREAD

**Issue by WhistleMaster** [kalkih/simple-weather-card#24]
Hi !

Thanks for the amazing work you do ! I've updated to latest version 0.7.2, but primary_info and secondary_info are not working. I'm using the following configuration:

```
backdrop: false
primary_info:
  - wind_bearing
  - humidity
secondary_info:
  - precipitation
  - precipitation_probability
custom:
  - temp: sensor.netatmo_outdoor_temperature
  - high: sensor.netatmo_outdoor_high_temp
  - low: sensor.netatmo_outdoor_min_temp
entity: weather.dark_sky
name: ' '
type: 'custom:simple-weather-card'
```

But I get the following error and the card is not displaying:

`TypeError: E[A] is undefined simple-weather-card-bundle.js:1:4519`

Thanks !

**Comment by kalkih** [comment]
Hello, thanks for your report.
The error does unfortunately not give me much information to go on.
Could you try starting with a very basic config, then add one option after the other and see at which point it breaks?

Start with e.g.
```yaml
type: custom:simple-weather-card
entity: weather.dark_sky
primary_info:
  - wind_bearing
  - humidity
```
Then
```yaml
type: custom:simple-weather-card
entity: weather.dark_sky
secondary_info:
  - precipitation
```

And so on...

Thank you!

**Comment by WhistleMaster** [comment]
The following give me a card, but the wrong info are displayed:
```
primary_info:
  - wind_bearing
  - humidity
secondary_info:
  - precipitation
custom:
  - temp: sensor.netatmo_outdoor_temperature
  - high: sensor.netatmo_outdoor_high_temp
  - low: sensor.netatmo_outdoor_min_temp
entity: weather.dark_sky
name: ' '
type: 'custom:simple-weather-card'
```
<img width="505" alt="Screenshot 2020-01-30 at 20 39 03" src="https://user-images.githubusercontent.com/1544568/73483897-9ad99300-43a0-11ea-9786-5e441f7df76a.png">

As soon as I had `precipitation_probability`, I got an empty card:
```
primary_info:
  - wind_bearing
  - humidity
secondary_info:
  - precipitation
  - precipitation_probability
custom:
  - temp: sensor.netatmo_outdoor_temperature
  - high: sensor.netatmo_outdoor_high_temp
  - low: sensor.netatmo_outdoor_min_temp
entity: weather.dark_sky
name: ' '
type: 'custom:simple-weather-card'
```
<img width="507" alt="Screenshot 2020-01-30 at 20 39 44" src="https://user-images.githubusercontent.com/1544568/73483936-b17fea00-43a0-11ea-88c8-cb15df3af9d3.png">
