### ISSUE TITLE
Error when simple-weather-card is in the stack

### ISSUE THREAD

**Issue by bieniu** [kalkih/simple-weather-card#38]
After update HA to 0.110.x I have a problem with the card. Sometimes, the error "Maximum call stack size exceeded" appears.

![Screenshot_20200525-212009](https://user-images.githubusercontent.com/478555/83324547-37844280-a266-11ea-9da3-501f144b3464.jpg)

I'm not sure if this error is related to `vertical-stack-in-card` or `simple-weather-card`. No other cards in `vertical-stack-in-card` display this error.

My config:
```
- type: custom:vertical-stack-in-card
  title: "Pogoda"
  cards:
    - type: custom:simple-weather-card
      entity: weather.dom
      tap_action:
        action: navigate
        navigation_path: /lovelace/climate
      name: " "
      primary_info:
        - humidity
        - precipitation_probability
      secondary_info:
        - pressure
      custom:
        - temp: sensor.temperature_outdoor
        - humidity: sensor.humidity_outdoor
        - pressure: sensor.pressure_outdoor
        - precipitation_probability: sensor.dark_sky_precip_probability
```
