### ISSUE TITLE
A way to specify day/ night sensor forcasts

### ISSUE THREAD

**Issue by ando023** [kalkih/simple-weather-card#39]
I have two sensors showing the day and night weather forecasts which work fine. However to see each forecast I have to have two cards setup. 

![Example](https://i.imgur.com/87FZsvZ.png)

Would it be possible to add additional options in **custom** options to allow for time of day sensors? 

Say something like this for example? 

```
- type: 'custom:simple-weather-card'
  custom:
    - entity: 
        day: sensor.wupws_weather_1d
        night: sensor.wupws_weather_1n
```

**Comment by ando023** [comment]
Figured an alternate way to achieve this. Closing the issue now, hopefully this might help someone in the future.

## Setup Binary Sensors
In home assistant there is [TimeOfDay(TOD)](https://www.home-assistant.io/integrations/tod/) binary sensors that can be created. 

To achieve a Day/ Night cycle I added the following to my `configuration.yaml`: 
```
binary_sensor:
  - platform: tod
    name: Night_Sensor
    after: sunset
    before: sunrise
  - platform: tod
    name: Day_Sensor
    after: sunrise
    before: sunset
  ```
After a restart of home assistant, you should now see two new binary sensors called;
* binary_sensor.night_sensor
* binary_sensor.day_sensor

Validate that each sensor displays the correct `on` or `off` function. If you have your day and night sensors showing as `on` or `off` you have configured your binary sensor wrong. Check the code and validate it again.

If you have done it correctly, you should have something like this;

![Off](https://i.imgur.com/vEEbrdS.png) ![On](https://i.imgur.com/zdX5p4Q.png)

## Configuring a Card in your Dashboard
In the card that you want to apply this too, copy the following;

```
- type: conditional
    conditions:
      - entity: binary_sensor.night_sensor
        state: 'on'
    card:
      type: 'custom:simple-weather-card'
      name: 'Night Forcast:'
      entity: sensor.wupws_weather_1n
      backdrop:
        day: '#f6ca69'
        night: '#568bd9'
  - type: conditional
    conditions:
      - entity: binary_sensor.day_sensor
        state: 'on'
    card:
      type: 'custom:simple-weather-card'
      name: 'Night Forcast:'
      entity: sensor.wupws_weather_1d
      backdrop:
        day: '#568bd9'
        night: '#f6ca69'
```

Based from the `on` or `off` status of either `binary_sensor.night_sensor` or `binary_sensor.day_sensor` enables the day or night versions of the forecast cards.
