### ISSUE TITLE
Wind Speed is always suffixed km/h

### ISSUE THREAD

**Issue by micaelp** [kalkih/simple-weather-card#63]
You can change the measured value in HA and the number displayed is right, but the unit is hard coded as km/h
![capture](https://user-images.githubusercontent.com/44983322/195135865-416ef1fa-ff9a-4432-ae5d-c981683c3ac6.png)

**Comment by chumbazoid** [comment]
Same for Pressure, units are always shown as hPa.

**Comment by mrtnnwmn** [comment]
The custom function should allow for the UoM to be edited/omitted from a custom attribute, or perhaps even for fully custom attributes.

Example:
```
# Custom units
custom:
  - precipitation_probability
    entity: sensor.minutecast # If not specified, standard entity will be used
    unit: ' ' # If not specified, standard units will be used

# Fully custom attribute
custom:
  - name: minutecast 
    entity: sensor.minutecast
    unit: ' '

secondary_info:
  - minutecast
```
