### ISSUE TITLE
request: custom background

### ISSUE THREAD

**Issue by QonosSWE** [kalkih/simple-weather-card#7]
I would love to add my own custom background-images

**Comment by kalkih** [comment]
You can achieve this with the help of [lovelace-card-modder](https://github.com/thomasloven/lovelace-card-modder), see [this](https://github.com/thomasloven/lovelace-card-modder#templates) example.

Or if you don't care about dynamically changing backgrounds, you could do something like this.
```yaml
- type: custom:card-modder
  style:
    background-image: "url(/local/example-bg.jpg)"
  card:
    type: custom:simple-weather-card
    entity: weather.example
```
