### ISSUE TITLE
Not yet compatible with weather.get_forecast service

### ISSUE THREAD

**Issue by caraar12345** [kalkih/simple-weather-card#72]
Hello!

Just a quick one - the new [`weather.get_forecast` service](https://www.home-assistant.io/integrations/weather/#service-weatherget_forecast) added in 2023.9 isn't yet used by `simple-weather-card`. Unfortunately some weather integrations have already moved to using that entirely rather than continuing to support the `forecast` state attribute (such as the [Apple WeatherKit](https://github.com/tjhorner/home-assistant-weatherkit) integration which will be native in 2023.10).

I'd love to be able to raise a PR to support it but JS is not my bag at all 😅 

Cheers!

**Comment by jakbutler** [comment]
+1 to this; the "extrema" (today's high / low) are not visible as a result of this. 

Here is a work-around, but I'd rather not have to use it.  Create a template in your `configation.yaml` (where `weather.home` is the name of your weather entity): 

```yaml
template:
  - trigger:
      - trigger: time_pattern
        hours: /1
    action:
      - action: weather.get_forecasts
        data:
          type: twice_daily
        target:
          entity_id: weather.home
        response_variable: twice_daily
    sensor:
      - name: High Temperature Forecast
        unique_id: temperature_forecast_high
        state: "{{ twice_daily['weather.home'].forecast[0].temperature }}"
        unit_of_measurement: °F
        icon: mdi:temperature-fahrenheit
        device_class: temperature
        state_class: measurement
      - name: Low Temperature Forecast
        unique_id: temperature_forecast_low
        state: "{{ twice_daily['weather.home'].forecast[1].temperature }}"
        unit_of_measurement: °F
        icon: mdi:temperature-fahrenheit
        device_class: temperature
        state_class: measurement
```
This will  create some Helper entities that will contain the daily high / low (updated every hour, which you can adjust as needed). 
Then, in your card, specify these values as custom overrides: 
```yaml
type: custom:simple-weather-card
entity: weather.home
name: Home
primary_info:
  - extrema
custom:
  - high: sensor.temperature_forecast_high
  - low: sensor.temperature_forecast_low
```
**PS:** I had to tweak the entity_ids to match the unique_id that I wanted, but whatever...

**EDIT:** Just in case the `twice_delay` request can return the night prediction before the day, the below logic will ensure correct high / low assignment: 

```yaml
      - name: High Temperature Forecast
        unique_id: temperature_forecast_high
        state: "{{ twice_daily['weather.home'].forecast[0:2] | map(attribute='temperature') | list | max }}"
        unit_of_measurement: °F
        icon: mdi:temperature-fahrenheit
        device_class: temperature
        state_class: measurement
      - name: Low Temperature Forecast
        unique_id: temperature_forecast_low
        state: "{{ twice_daily['weather.home'].forecast[0:2] | map(attribute='temperature') | list | min }}"
        unit_of_measurement: °F
        icon: mdi:temperature-fahrenheit
        device_class: temperature
        state_class: measurement
```
